### ISSUE TITLE
Maximum m/z in compute-fragmentation-trees

### ISSUE THREAD

**Issue by helenamrusso** [biocore/q2-qemistree#143]
@anupriyatripathi @ElDeveloper 
There is a limit of m/z in the compute-fragmentation-trees step. It should be interesting to increase this value (maybe to ~m/z 1200 or so?) since some groups can be characterized by several glycosyl units, for instance.

_qiime qemistree compute-fragmentation-trees \
  --i-features Malpighiaceae_Filtered_EtOH80_NEG_Sirius_MergeMSMS.mgf.qza \
  --p-sirius-path 'sirius-osx64-headless-4.0.1/bin' \
  --p-n-jobs 8 \
  --p-ppm-max 20 \
  --p-profile qtof \
  --p-maxmz **1000** \
  --p-ionization-mode negative \
  --p-java-flags '-Djava.io.tmpdir=/Users/helenarusso/ -Xms45G -Xmx60G' \
  --o-fragmentation-trees Malpighiaceae_EtOH80_NEG_fragmentation_trees_test1000.qza \
  --verbose_

If we put a value above 850, we get an error:

**bash: line 2: activate: No such file or directory**
Traceback (most recent call last):
  File "/Users/helenarusso/opt/miniconda3/envs/qiime2-2020.2/lib/python3.6/site-packages/q2cli/commands.py", line 328, in __call__
    results = action(**arguments)
  File "</Users/helenarusso/opt/miniconda3/envs/qiime2-2020.2/lib/python3.6/site-packages/decorator.py:decorator-gen-211>", line 2, in compute_fragmentation_trees
  File "/Users/helenarusso/opt/miniconda3/envs/qiime2-2020.2/lib/python3.6/site-packages/qiime2/sdk/action.py", line 208, in bound_callable
    self.signature.check_types(**user_input)
  File "/Users/helenarusso/opt/miniconda3/envs/qiime2-2020.2/lib/python3.6/site-packages/qiime2/core/type/signature.py", line 354, in check_types
    % (name, parameter, spec.qiime_type))
TypeError: Parameter 'maxmz' received 1000 as an argument, which is incompatible with parameter type: Int % Range(100, 850, inclusive_end=True)

**Plugin error from qemistree:**

  **Parameter 'maxmz' received 1000 as an argument, which is incompatible with parameter type: Int % Range(100, 850, inclusive_end=True)**

See above for debug info.

**Comment by ElDeveloper** [comment]
Looks like @anupriyatripathi closed this issue in #144. Thanks both!
