### ISSUE TITLE
Plugin error from qemistree:    [Errno 2] No such file or directory: '/tmp/qiime2-archive-jo4eaqoo/881ea900-5aef-49db-9408-d5edb694d63d/data/csi-output

### ISSUE THREAD

**Issue by YUANMY2021** [biocore/q2-qemistree#152]
Whether running the demo data or my own data

Will always produce the error like this:

Traceback (most recent call last):
  File "/share/home/jianglab/yuanmengyi/miniconda2/envs/qiime2-2021.2/lib/python3.6/site-packages/q2cli/commands.py", line 329, in __call__
    results = action(**arguments)
  File "<decorator-gen-223>", line 2, in make_hierarchy
  File "/share/home/jianglab/yuanmengyi/miniconda2/envs/qiime2-2021.2/lib/python3.6/site-packages/qiime2/sdk/action.py", line 245, in bound_callable
    output_types, provenance)
  File "/share/home/jianglab/yuanmengyi/miniconda2/envs/qiime2-2021.2/lib/python3.6/site-packages/qiime2/sdk/action.py", line 390, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/share/home/jianglab/yuanmengyi/miniconda2/envs/qiime2-2021.2/lib/python3.6/site-packages/q2_qemistree/_hierarchy.py", line 126, in make_hierarchy
    qc_properties, metric)
  File "/share/home/jianglab/yuanmengyi/miniconda2/envs/qiime2-2021.2/lib/python3.6/site-packages/q2_qemistree/_process_fingerprint.py", line 95, in process_csi_results
    collated_fps = collate_fingerprint(csi_result, qc_properties, metric)
  File "/share/home/jianglab/yuanmengyi/miniconda2/envs/qiime2-2021.2/lib/python3.6/site-packages/q2_qemistree/_process_fingerprint.py", line 28, in collate_fingerprint
    fpfoldrs = os.listdir(csi_result)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/qiime2-archive-jo4eaqoo/881ea900-5aef-49db-9408-d5edb694d63d/data/csi-output'

Plugin error from qemistree:

  [Errno 2] No such file or directory: '/tmp/qiime2-archive-jo4eaqoo/881ea900-5aef-49db-9408-d5edb694d63d/data/csi-output'

See above for debug info

**Comment by chi-med-pro** [comment]
I met the same issue while performing `qiime qemistree make-hierarchy`.
```
Traceback (most recent call last):
  File "/home/echo/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/q2cli/commands.py", line 339, in __call__
    results = action(**arguments)
  File "<decorator-gen-462>", line 2, in make_hierarchy
  File "/home/echo/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/qiime2/sdk/action.py", line 245, in bound_callable
    outputs = self._callable_executor_(scope, callable_args,
  File "/home/echo/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/qiime2/sdk/action.py", line 391, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/home/echo/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/q2_qemistree/_hierarchy.py", line 121, in make_hierarchy
    collated_fps, smiles = process_csi_results(csi_result, None, metric)
  File "/home/echo/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/q2_qemistree/_process_fingerprint.py", line 88, in process_csi_results
    collated_fps = collate_fingerprint(csi_result, metric)
  File "/home/echo/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/q2_qemistree/_process_fingerprint.py", line 28, in collate_fingerprint
    fpfoldrs = os.listdir(csi_result)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/qiime2-archive-59aenzbm/34a7958c-668f-4b9c-9a45-c626e9b1bc66/data/csi-output'
```

**Comment by ElDeveloper** [comment]
In the past I've seen this error when there's a problem with CSI or the underlying tools being run. IIRC CSI sometimes fails due to connectivity issues. Can you try rerunning the command on a smaller set of the data? @anupriyatripathi any other suggestions?
