### ISSUE TITLE
Error with command qiime qemistree make-hierarchy

### ISSUE THREAD

**Issue by anani-a-missinou** [biocore/q2-qemistree#157]
Hi dear developers,

I was very excited to use your tools, everything was fine until I got this error from running **qemistree make-hierarchy**

I also try to run this command with your file from the tutorial, but I get the same error. I will send you the details of the error in the hope that you understand where it comes from.

(qiime2-shotgun-2023.9) $ **qiime qemistree make-hierarchy --i-csi-results features_pacs_pos_fingerprints.qza --i-feature-tables features_pacs_pos-table_hdf5.qza --o-tree features_pacs_pos-qemistree.qza --o-feature-table features_pacs_pos-table-hashed.qza --o-feature-data features_pacs_pos-data.qza**
Plugin error from qemistree:

  [Errno 2] No such file or directory: '/tmp/qiime2/amissinou/data/d5b2035f-8a82-471f-b757-31724593ff2e/data/csi-output'

Debug info has been saved to /tmp/qiime2-q2cli-err-9gxctqzh.log
(qiime2-shotgun-2023.9) $ more /tmp/qiime2-q2cli-err-9gxctqzh.log
Traceback (most recent call last):
  File "/home/amissinou/miniconda3/envs/qiime2-shotgun-2023.9/lib/python3.8/site-packages/q2cli/commands.py", line 520, in __call__
    results = self._execute_action(
  File "/home/amissinou/miniconda3/envs/qiime2-shotgun-2023.9/lib/python3.8/site-packages/q2cli/commands.py", line 581, in _execute_action
    results = action(**arguments)
  File "<decorator-gen-440>", line 2, in make_hierarchy
  File "/home/amissinou/miniconda3/envs/qiime2-shotgun-2023.9/lib/python3.8/site-packages/qiime2/sdk/action.py", line 342, in bound_callable
    outputs = self._callable_executor_(
  File "/home/amissinou/miniconda3/envs/qiime2-shotgun-2023.9/lib/python3.8/site-packages/qiime2/sdk/action.py", line 566, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/home/amissinou/miniconda3/envs/qiime2-shotgun-2023.9/lib/python3.8/site-packages/q2_qemistree/_hierarchy.py", line 118, in make_hierarchy
    collated_fps, smiles = process_csi_results(csi_result, None, metric)
  File "/home/amissinou/miniconda3/envs/qiime2-shotgun-2023.9/lib/python3.8/site-packages/q2_qemistree/_process_fingerprint.py", line 88, in process_csi_results
    collated_fps = collate_fingerprint(csi_result, metric)
  File "/home/amissinou/miniconda3/envs/qiime2-shotgun-2023.9/lib/python3.8/site-packages/q2_qemistree/_process_fingerprint.py", line 28, in collate_fingerprint
    fpfoldrs = os.listdir(csi_result)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/qiime2/amissinou/data/d5b2035f-8a82-471f-b757-31724593ff2e/data/csi-output'

Thank you for your help

**Comment by anani-a-missinou** [comment]
**(qiime2-shotgun-2023.9) $ mkdir -p /tmp/qiime2/amissinou/data/d5b2035f-8a82-471f-b757-31724593ff2e/data/csi-output**
**(qiime2-shotgun-2023.9) $ qiime qemistree make-hierarchy --i-csi-results features_pacs_pos_fingerprints.qza --i-feature-tables features_pacs_pos-table_hdf5.qza --o-tree features_pacs_pos-qemistree.qza --o-feature-table features_pacs_pos-table-hashed.qza --o-feature-data features_pacs_pos-data.qza**
Traceback (most recent call last):
  File "/home/amissinou/miniconda3/envs/qiime2-shotgun-2023.9/lib/python3.8/site-packages/qiime2/core/archive/archiver.py", line 118, in _get_versions
    with self.open(self.VERSION_FILE) as fh:
  File "/home/amissinou/miniconda3/envs/qiime2-shotgun-2023.9/lib/python3.8/site-packages/qiime2/core/archive/archiver.py", line 248, in open
    return open(os.path.join(self.path, relpath))
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/qiime2/amissinou/data/d5b2035f-8a82-471f-b757-31724593ff2e/VERSION'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amissinou/miniconda3/envs/qiime2-shotgun-2023.9/lib/python3.8/site-packages/q2cli/util.py", line 488, in _load_input_file
    artifact = qiime2.sdk.Result.load(fp)
  File "/home/amissinou/miniconda3/envs/qiime2-shotgun-2023.9/lib/python3.8/site-packages/qiime2/sdk/result.py", line 76, in load
    archiver = cache._load_uuid(peek.uuid)
  File "/home/amissinou/miniconda3/envs/qiime2-shotgun-2023.9/lib/python3.8/site-packages/qiime2/core/cache.py", line 955, in _load_uuid
    return Archiver.load_raw(path, self)
  File "/home/amissinou/miniconda3/envs/qiime2-shotgun-2023.9/lib/python3.8/site-packages/qiime2/core/archive/archiver.py", line 385, in load_raw
    archive = cls.get_archive(filepath)
  File "/home/amissinou/miniconda3/envs/qiime2-shotgun-2023.9/lib/python3.8/site-packages/qiime2/core/archive/archiver.py", line 320, in get_archive
    archive = _NoOpArchive(filepath)
  File "/home/amissinou/miniconda3/envs/qiime2-shotgun-2023.9/lib/python3.8/site-packages/qiime2/core/archive/archiver.py", line 92, in __init__
    self.version, self.framework_version = self._get_versions()
  File "/home/amissinou/miniconda3/envs/qiime2-shotgun-2023.9/lib/python3.8/site-packages/qiime2/core/archive/archiver.py", line 128, in _get_versions
    raise ValueError("Archive does not contain a correctly formatted"
ValueError: Archive does not contain a correctly formatted VERSION file.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amissinou/miniconda3/envs/qiime2-shotgun-2023.9/lib/python3.8/site-packages/q2cli/click/type.py", line 116, in _convert_input
    result, error = q2cli.util._load_input(value)
  File "/home/amissinou/miniconda3/envs/qiime2-shotgun-2023.9/lib/python3.8/site-packages/q2cli/util.py", line 397, in _load_input
    artifact, error = _load_input_file(fp)
  File "/home/amissinou/miniconda3/envs/qiime2-shotgun-2023.9/lib/python3.8/site-packages/q2cli/util.py", line 494, in _load_input_file
    raise ValueError(
ValueError: It looks like you have an Artifact but are missing the plugin(s) necessary to load it. Artifact has type 'CSIFolder' and format 'CSIDirFmt'

There was a problem loading 'features_pacs_pos_fingerprints.qza' as an artifact:

  It looks like you have an Artifact but are missing the plugin(s) necessary to load it. Artifact has type 'CSIFolder' and format 'CSIDirFmt'

See above for debug info.

**(qiime2-shotgun-2023.9) $ qiime tools peek features_pacs_pos_fingerprints.qza**

UUID:        d5b2035f-8a82-471f-b757-31724593ff2e
Type:        CSIFolder
Data format: CSIDirFmt

**Comment by anupriyatripathi** [comment]
@Mannochio Russo, Helena ***@***.***> might have used
this recently and could likely help!

Anupriya Tripathi
Principal AI Scientist, Genentech <https://www.gene.com/>

**Comment by anani-a-missinou** [comment]
Ok, thank you @anupriyatripathi for your response.

@helenamrusso, I appreciate your help. 

Thank you

**Comment by mcmk3** [comment]
Hi,
@anani-a-missinou and @helenamrusso did you ever find a solution to this issue? I'm running into exactly the same problem...
Thank you!

**Comment by anani-a-missinou** [comment]
Hi @mcmk3,

No, I waited a long time without receiving any response. I finally tried to solve it myself, but without success.

Please inform me if you successfully resolve this. Thanks

**Comment by helenamrusso** [comment]
The last time I used Qemistree was using this branch for sirius5: https://github.com/biocore/q2-qemistree/tree/sirius5

I have not used Qemistree with SIRIUS6 outputs. I believe @Phytoecia (Minsoo Choi) is the one who has been using Qemistree lately, so I would recommend contacting him for more information. More information here https://github.com/Phytoecia/PyQemistree

**Comment by mcmk3** [comment]
Thanks @helenamrusso (and @Phtoecia)
I tried the version developed by @Phytoecia (Minsoo Choi, https://github.com/Phytoecia/PyQemistree) and while I had some initial issues with getting it to run Sirius, the extraction of fingerprints and creation of a distance matrix using the later part of the script on an existing Sirius project I just ran with the normal Sirius6 seems to have worked!
